### ISSUE TITLE
Run hydra janitor

### ISSUE THREAD

**Issue by nsklikas** [canonical/hydra-operator#40]
### Enhancement Proposal

We need to provide a mechanism for cleaning up the database. Hydra offers the `hydra janitor` [command](https://www.ory.sh/docs/hydra/cli/hydra-janitor). Ideally we would like to run this periodically (cronjob?), but we need to first gather some data about and investigate about how often it needs to be run, etc.

**Comment by shipperizer** [comment]
feature could be implemented as a routine `juju action` or command and specified in the maintenance documentation

only needed for a certain customer scale, therefore dropping for the time being
