### ISSUE TITLE
Rename interface name to something more specific to hydra

### ISSUE THREAD

**Issue by bencekov** [canonical/hydra-operator#46]
### Enhancement Proposal

Maybe it would be wise to rename the interface name to something more specific to hydra since the introduction of similar interfaces in the bundle. My proposal would be hydra_endpoints

**Comment by natalian98** [comment]
Thanks for opening this enhancement proposal @bencekov.

This generic relation name was given when we planned to implement the other relation interfaces differently. I agree it's a good idea to rename it - I think `hydra-endpoint-info` would follow the usual relations naming convention @gruyaume?
If we decide to rename it, it needs to be changed in `kratos-operator` (the requirer) as well.

**Comment by nsklikas** [comment]
I think that this is fixed by https://github.com/canonical/hydra-operator/commit/2953db263f8ac843f64281d01f413d7a71285220. 

Can we close it @bencekov?
